@TodoApi_HostAddress = http://localhost:5197
Post {{TodoApi_HostAddress}}/todoitems
Content-Type: application/json

{
  "name":"walk dog",
  "isComplete":true
}

###

GET {{TodoApi_HostAddress}}/todoitems

###

GET {{TodoApi_HostAddress}}/todoitems/complete

###

PUT {{TodoApi_HostAddress}}/todoitems/1
Content-Type: application/json

{
  "name":"walk dog",
  "isComplete":false
}
###
